openapi: "3.0.0"
info:
  title: Hermet API
  version: 1.1.0
  description: Service for the smart API stubbing
paths:
  /api/services:
    get:
      summary: Services list
      tags:
        - Services
      responses:
        '200':
          description: Array of services
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Service'
    post:
      summary: Create new service
      tags:
        - Services
      requestBody:
        description: Service details
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - targetUrl
              properties:
                name:
                  type: string
                  description: Service name. Must be unique.
                targetUrl:
                  type: string
                  description: Proxy target url
                ttl:
                  type: integer
                  description: Time to life in seconds
                  nullable: true
      responses:
        '201':
          description: Service created

  /api/services/{service_id}:
    get:
      summary: Get service by id
      tags:
        - Services
      parameters:
        - name: service_id
          in: path
          description: ID of service to fetch
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Service details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Service'
    put:
      summary: Update service details
      tags:
        - Services
      parameters:
        - name: service_id
          in: path
          description: ID of service to fetch
          required: true
          schema:
            type: string
      requestBody:
        description: Service details
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: Service name. Must be unique.
                targetUrl:
                  type: string
                  description: Proxy target url
                ttl:
                  type: integer
                  description: Time to life in seconds
                  nullable: true
      responses:
        '204':
          description: Service updated

    delete:
      summary: Update service details
      tags:
        - Services
      parameters:
        - name: service_id
          in: path
          description: ID of service to fetch
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Service deleted
  /api/services/{service_id}/stubs:
    get:
      summary: Get stubs list
      tags:
        - Stubs
      parameters:
        - name: service_id
          in: path
          description: ID of service to fetch
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Stubs list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Stub'
    post:
      summary: Create new stub
      tags:
        - Stubs
      parameters:
        - name: service_id
          in: path
          description: ID of service to fetch
          required: true
          schema:
            type: string
      requestBody:
        description: Stub details
        content:
          application/json:
            schema:
              type: object
              required:
                - serviceId
                - response
                - predicates
              properties:
                serviceId:
                  type: string
                  description: Service ID
                response:
                  $ref: '#/components/schemas/StubbedResponse'
                predicates:
                  type: array
                  description: Array of predicates
                  items:
                    type: object
                ttl:
                  type: integer
                  description: Time to life in seconds
                  nullable: true
      responses:
        '201':
          description: Stub created

    delete:
      summary: Delete all stubs from the service
      tags:
        - Stubs
      parameters:
        - name: service_id
          in: path
          description: ID of service to fetch
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Stubs deleted

  /api/services/{service_id}/stubs/{stub_id}:
    get:
      summary: Get stub by id
      tags:
        - Stubs
      parameters:
        - name: service_id
          in: path
          description: ID of service to fetch
          required: true
          schema:
            type: string
        - name: stub_id
          in: path
          description: ID of stub to fetch
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Stub details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Stub'
    put:
      summary: Update stub details
      tags:
        - Stubs
      parameters:
        - name: service_id
          in: path
          description: ID of service to fetch
          required: true
          schema:
            type: string
        - name: stub_id
          in: path
          description: ID of stub to fetch
          required: true
          schema:
            type: string
      requestBody:
        description: Stub details
        content:
          application/json:
            schema:
              type: object
              properties:
                response:
                  $ref: '#/components/schemas/StubbedResponse'
                predicates:
                  type: array
                  description: Array of predicates
                  items:
                    type: object
                ttl:
                  type: integer
                  description: Time to life in seconds
                  nullable: true
      responses:
        '204':
          description: Stub updated

    delete:
      summary: Delete stub by id
      tags:
        - Stubs
      parameters:
        - name: service_id
          in: path
          description: ID of service to fetch
          required: true
          schema:
            type: string
        - name: stub_id
          in: path
          description: ID of stub to fetch
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Stub deleted
  /api/stubs:
    delete:
      summary: Delete all stubs
      tags:
        - Stubs
      responses:
        '204':
          description: Stubs deleted

  /api/flush:
    post:
      tags:
        - Database Reset
      summary: Global database reset
      description: Will delete all stubs and services
      responses:
        '204':
          description: Database flush success

components:
  schemas:
    BaseModel:
      properties:
        $loki:
          type: string
          description: internal DB index (to be removed)
        id:
          type: string
          description: Unique identifier
        createAt:
          type: string
          nullable: true
          description: Creation time
        expireAt:
          type: string
          nullable: true
          description: Expiration time
        ttl:
          type: integer
          description: Time to life in seconds

    Service:
      allOf:
        - $ref: '#/components/schemas/BaseModel'
        - properties:
            name:
              type: string
              description: Service name. Must be unique.
            targetUrl:
              type: string
              description: Proxy target url

    Stub:
      allOf:
        - $ref: '#/components/schemas/BaseModel'
        - properties:
            serviceId:
              type: string
              description: Service ID
            response:
              $ref: '#/components/schemas/StubbedResponse'
            predicates:
              type: array
              description: Array of predicates
              items:
                type: object

    StubbedResponse:
      properties:
        statusCode:
          type: integer
          description: Stub response code
        headers:
          type: object
          additionalProperties:
            type: string
        body:
          oneOf:
            - type: object
            - type: string
          nullable: true
